FDP-1622 ~ Adds initial version of proxy
OSGP/sng-coap-http-proxy pull request #1
Opened 2023-10-13 14:33 UTC by smvdheijden

2023-10-16 08:09 UTC, LucianoFavoroso commented on components/sng-coap-http-proxy-adapter-coap-server/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/server/CoapResource.kt
> +            logger.debug("Device ID from request context: $deviceId")
logger.debug {} gebruiken

2023-10-16 09:53 UTC, jasperkamerling requested changes

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-server/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/server/CoapServer.kt
> +    fun shutDown() {
Deze functie wordt niet gebruikt. moet waarschijnlijk met spring hooks gedaan worden

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-server/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/server/CoapServer.kt
> +    init {
Dit liever in een spring bean hook

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-server/src/main/resources/application.yaml
> +
Dit lijkt me geen productie config, kan in een dev profile

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-server/src/test/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/server/configuration/properties/CoapPropertiesTest.kt
> +class CoapPropertiesTest() {
we hoeven niet de Spring ConfigurationProperties te testen, dus deze test is overbodig.

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-server/src/test/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/server/configuration/properties/UdpPropertiesTest.kt
> +class UdpPropertiesTest(@Autowired val udpProperties: UdpProperties) {
we hoeven niet de Spring ConfigurationProperties te testen, dus deze test is overbodig.

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-server/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/server/configuration/CoapConfiguration.kt
> +            set(CoapConfig.MAX_ACTIVE_PEERS, coapProps.maxActivePeers)
Set is een build hoeft niet in een config

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-test-client/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/test/client/CoapClientConfiguration.kt
> +    @Bean("clientConfiguration")
bean naam is overbodig

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-coap-test-client/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/coap/test/client/CoapClientConfiguration.kt
> +    fun invalidCoapClient(clientConfiguration: CaliforniumConfiguration) = CoapClient(COAP_URI)
Waarom hebben we een invalid config in productie code?

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/application/ports/input/CoapMessageInputPort.kt
> +fun interface CoapMessageInputPort {
onnodige interface

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/application/ports/output/HttpMessageOutputPort.kt
> +fun interface HttpMessageOutputPort {
onnodige interface

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/application/ports/output/PskRepositoryOutputPort.kt
> +fun interface PskRepositoryOutputPort {
onnodige interface

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-http-client/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/adapter/http/client/configuration/HttpsConfiguration.kt
> +class HttpsConfiguration() {
https en http configuratie hoeven we niet in een losse configuration class te doen.

2023-10-16 09:53 UTC, jasperkamerling commented on components/sng-coap-http-proxy-adapter-http-client/src/main/resources/ssl/truststore.jks
Ik heb liever geen test truststores in de productie code.

2023-10-20 13:44 UTC, jasperkamerling requested changes

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/configuration/CoapConfiguration.kt
> +@EnableConfigurationProperties(value = [CoapProperties::class, UdpProperties::class])
dit staat al in de main application class

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/configuration/CoapConfiguration.kt
> +    fun pskStore(pskStoreStub: PskStoreStub) = AdvancedMultiPskStore()
dit kan ook gewoon in een single store, maar hoeft niet perse omdat we het binnenkort gaan vervangen

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/CoapMessageHandler.kt
> +        logger.warn { "Received invalid message: $message" }
Deze error loggen we ook al bij de exception afhandeling

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/CoapResource.kt
> +            logger.debug("Device ID from request context: $deviceId")
{}

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/CoapResource.kt
> +class CoapResource(private val coapProps: CoapProperties, private val coapMessageHandler: CoapMessageHandler) :
Ik zet liever meer van deze afhandeling in de message handler en laat hier alleen de echt coap dingen staan.

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/CoapServer.kt
> +    )
Ik heb deze twee functies liever bij de andere configuratie. Dan hoeven we hier de properties niet te hebben

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/domain/Message.kt
> +    override fun toString() = "Message[ deviceId=\"$deviceId\", payload=\"${payload}\" ]"
toString is niet nodig

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/http/configuration/properties/HttpProperties.kt
> +        val protocol: String,
Protocol kan ook gewoon bij de url

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/http/configuration/properties/HttpProperties.kt
> +package org.gxf.standalonenotifyinggateway.coaphttpproxy.adapter.http.client.configuration.properties
package klopt niet

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/http/configuration/properties/HttpProperties.kt
> +        val sslBundle: String,
sslBundle kan optioneel zijn

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/http/HttpClient.kt
> +                .uri { uriBuilder -> uriBuilder.path(id).build() }
dit kan ook gewoon: `.uri("/${id}")` zijn

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/CoapHttpProxyApplication.kt
> +@EnableConfigurationProperties(CoapProperties::class, UdpProperties::class, HttpProperties::class, PskStubProperties::class)
dit kan ook gescand worden met `@ConfigurationPropertiesScan` dan hoeven ze hier niet allemaal te staan.

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/test/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/MessageValidatorTest.kt
> +@ExtendWith(MockitoExtension::class)
Dit heeft geen mockito nodig

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/resources/application-dev.yaml
> +      max-history: 30
In de hoeven we niet naar log files te loggen

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/resources/application-dev.yaml
> +    org.eclipse.californium: warn
hebben we deze waardes nodig in dev?

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/resources/application-dev.yaml
> +    health-status-interval-unit: SECONDS
unit hebben we niet

2023-10-20 13:44 UTC, jasperkamerling commented on application/src/main/resources/application-dev.yaml
> +    health-status-interval: 60
achter een duration graag een unit

2023-10-23 06:56 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/configuration/CoapConfiguration.kt
> +    fun pskStore(pskStoreStub: PskStoreStub) = AdvancedMultiPskStore()
In verband met de snelle vervanging ga ik dit nu niet aanpassen, mits akkoord natuurlijk

2023-10-23 12:07 UTC, jasperkamerling requested changes

2023-10-23 12:15 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/configuration/CoapConfiguration.kt
> +    fun dtlsConnector(config: CaliforniumConfiguration, pskStore: AdvancedMultiPskStore) = DTLSConnector(
Besproken dat dit niet nodig is in dit geval

2023-10-23 15:03 UTC, jasperkamerling approved these changes

2023-10-23 15:12 UTC, merged