OPS: Spotless formatter added
OSGP/sng-coap-http-proxy pull request #10
Opened 2024-02-23 08:21 UTC by sanderv

2024-04-17 08:00 UTC, sanderv commented on application/build.gradle.kts
> +                    implementation(
Kunnen we hier nog iets doen met de regellengte? Of een andere schrijfwijze, ik vind 'm verbose.

2024-04-17 08:00 UTC, sanderv commented on application/build.gradle.kts
> +                        "org.mock-server:mockserver-spring-test-listener:${rootProject.extra["mockServerVersion"]}",
extra komma's aan het einde van de regel (x3)

2024-04-17 08:08 UTC, loesimmens commented on application/build.gradle.kts
> +                    implementation(
nee, die kunnen we helaas niet aanpassen bij ktfmt, anders had ik hem op 120 gezet (is nu 100)

2024-04-17 08:11 UTC, jasperkamerling commented on application/build.gradle.kts
> +                    implementation(
Misschien kunnen we de `*.gradle.kts` files excluden van spotless.

2024-04-17 08:12 UTC, loesimmens commented on application/build.gradle.kts
> +                        "org.mock-server:mockserver-spring-test-listener:${rootProject.extra["mockServerVersion"]}",
De trailing comma is een Kotlin coding convention (https://kotlinlang.org/docs/coding-conventions.html#trailing-commas). Ik denk dat dit bij het type Any voor de zekerheid ook wordt doorgevoerd (en dus ook compileert).

2024-04-17 08:13 UTC, jasperkamerling commented on application/build.gradle.kts
> +                    implementation(
Of misschien moeten we dit oplossen door het op te nemen in de settings.gradle.kts, dan wordt de regel ook minder lang

2024-04-17 08:22 UTC, jasperkamerling commented on application/build.gradle.kts
> +                        "org.mock-server:mockserver-spring-test-listener:${rootProject.extra["mockServerVersion"]}",
Het lijkt er op dat ktfmt niet goed doorheeft dat dit ook een string is zoals de regel erboven omdat er een variabele inzit.
De regel er boven betekent precies hetzelfde maar heeft geen komma.

2024-05-29 09:12 UTC, jasperkamerling requested changes

2024-05-29 09:12 UTC, jasperkamerling commented on build.gradle.kts
> +                    .trimIndent(),
Graag opnemen in een file zoals bij de `sng-io-file-processor`

2024-05-29 10:15 UTC, jasperkamerling approved these changes

2024-05-29 11:19 UTC, LucianoFavoroso approved these changes

2024-05-29 11:19 UTC, merged