FDP-2327: Adding kubernetes probes + specific port
OSGP/sng-coap-http-proxy pull request #24
Opened 2024-06-27 15:32 UTC by JelleHoffman

2024-06-27 16:00 UTC, jasperkamerling approved these changes

2024-06-27 16:01 UTC, jasperkamerling requested changes

2024-06-27 16:01 UTC, jasperkamerling commented on application/src/main/resources/application.yaml
> +    port: 8081
De coap-http-proxy is niet bereikbaar onder normaal http verkeer, alleen met coap

2024-06-28 09:15 UTC, smvdheijden approved these changes

2024-06-28 09:24 UTC, merged