FDP-1628: added remote psk store
OSGP/sng-coap-http-proxy pull request #5
Opened 2023-11-14 09:50 UTC by LucianoFavoroso

2023-11-16 18:50 UTC, smvdheijden requested changes

2023-11-16 19:06 UTC, smvdheijden requested changes

2023-11-16 19:06 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/configuration/psk/RemotePskStore.kt
> +package org.gxf.standalonenotifyinggateway.coaphttpproxy.coap.configuration.psk
Missing license header

2023-11-21 08:15 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/configuration/CoapConfiguration.kt
> +            RemotePskStore(webClient, remoteLogger)
Removed bean, it is not needed for correct initialization.

2023-11-21 08:25 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/coap/configuration/psk/RemotePskStore.kt
> +package org.gxf.standalonenotifyinggateway.coaphttpproxy.coap.configuration.psk
Added header but github doesn't show outdated

2023-11-21 10:52 UTC, JelleHoffman approved these changes

2023-11-21 13:15 UTC, sanderv commented on application/src/integrationTest/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/IntegrationTest.kt
>      @Value("\${config.psk.default-id}")
Waarom gebruik je hier niet gewoon `PskStubProperties`?

2023-12-04 14:31 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/standalonenotifyinggateway/coaphttpproxy/MessageHandlerTest.kt
> +            assertThat(message).usingRecursiveComparison().isEqualTo(it)
Wrong order of actual object under test and the expected value.
```suggestion
            assertThat(it).usingRecursiveComparison().isEqualTo(message)
```

2023-12-04 14:33 UTC, smvdheijden commented on application/build.gradle.kts
> +    testImplementation("org.assertj:assertj-core:3.24.2")
Isn't the version provided by Spring Boot?

2023-12-05 13:15 UTC, smvdheijden approved these changes

2023-12-05 13:15 UTC, merged